name = "chat-summary"
compatibility_date = "2023-12-01"
main = "./functions/_middleware.js"

[build]
command = "npm run build"

[site]
bucket = "./templates"

[env.production]
vars = { NODE_ENV = "production" }

# KV命名空间配置
[[kv_namespaces]]
binding = "CHAT_ANALYSIS_STORAGE"
id = "94bb588f7514891b5f6ea569af482c08"

# 环境变量
[vars]
DEEPSEEK_API_KEY = "sk-902bac46d4f44d81a6089ff095401a6d"
DEEPSEEK_MODEL = "deepseek-chat"
