name = "chat-summary"
compatibility_date = "2023-12-01"
main = "./functions/_middleware.js"

[build]
command = "npm run build"

[site]
bucket = "./templates"

[env.production]
vars = { NODE_ENV = "production" }

# 注意：您需要在Cloudflare控制台创建KV命名空间，并将ID替换到下面
[[kv_namespaces]]
binding = "CHAT_ANALYSIS_STORAGE"
id = "your-kv-namespace-id"  # 这个ID需要从Cloudflare控制台获取

# 环境变量
[vars]
DEEPSEEK_API_KEY = "sk-902bac46d4f44d81a6089ff095401a6d"
DEEPSEEK_MODEL = "deepseek-chat"
